#!/usr/bin/env node
'use strict';
/**
 * graph_dashboard.js — one page showing what the graph actually holds.
 *
 * ─────────────────────────────────────────────────────────────────────
 * WHY THIS IS NOT A PICTURE OF THE NETWORK
 * ─────────────────────────────────────────────────────────────────────
 * The obvious dashboard for a graph is the graph: nodes, edges, a force
 * layout, everything connected to everything. It looks like an investigation
 * and it answers no question. With 1,500 organisations it is a hairball, and
 * a hairball invites the reader to see structure that is an artifact of the
 * layout algorithm.
 *
 * So this charts the small number of things the graph can actually answer:
 *
 *   - which firms carry more than one client (the only question the sworn
 *     data supports on its own)
 *   - which of those carry clients on BOTH sides of the question being
 *     investigated
 *   - how much of the library each search contributed, which is a fact about
 *     the SEARCHING, not about the world
 *
 * ─────────────────────────────────────────────────────────────────────
 * EVERY NUMBER HERE IS A FLOOR
 * ─────────────────────────────────────────────────────────────────────
 * Captures stop at the source's page size, and roughly two in five hold
 * fewer rows than the source said existed. A dashboard is exactly where that
 * gets forgotten, because a bar chart looks complete. So the shortfall is
 * stated at the top, in the same type size as the totals, rather than in a
 * footnote.
 *
 * Self-contained: no script, no CDN, no font host, no request of any kind.
 * It opens with the Wi-Fi off and it will still open in five years.
 */

const CH = require('./lobby_chart.js');

/** Firms carrying more than one client, most clients first. */
function multiClientRegistrants(graph) {
  const byReg = new Map();
  const nameOf = new Map(graph.orgs.map((o) => [o.key, o.name]));
  for (const f of graph.filed) {
    if (!byReg.has(f.registrant)) byReg.set(f.registrant, { clients: new Map(), filings: 0 });
    const g = byReg.get(f.registrant);
    g.clients.set(f.client, (g.clients.get(f.client) || 0) + f.filings);
    g.filings += f.filings;
  }
  const out = [];
  for (const [key, g] of byReg) {
    if (g.clients.size < 2) continue;
    out.push({
      key,
      name: nameOf.get(key) || key,
      clientCount: g.clients.size,
      filings: g.filings,
      clients: [...g.clients.entries()]
        .map(([k, n]) => ({ name: nameOf.get(k) || k, filings: n }))
        .sort((a, b) => b.filings - a.filings),
    });
  }
  return out.sort((a, b) => b.clientCount - a.clientCount || b.filings - a.filings);
}

/**
 * Firms whose clients straddle two named sides of a question.
 *
 * The patterns are supplied rather than built in: what counts as "both sides"
 * is a property of the investigation, not of lobbying data, and a tool that
 * decided it for you would be smuggling in an editorial judgement as though
 * it were arithmetic.
 */
function straddling(rows, sideA, sideB) {
  const hit = (list, re) => list.some((c) => re.test(c.name.toUpperCase()));
  return rows.filter((r) => hit(r.clients, sideA) && hit(r.clients, sideB));
}

/** How much each search contributed. A fact about the searching. */
function bySubject(graph) {
  const counts = new Map();
  for (const a of graph.appears) {
    counts.set(a.subject, (counts.get(a.subject) || 0) + 1);
  }
  return [...counts.entries()]
    .map(([label, value]) => ({ label, value }))
    .sort((a, b) => b.value - a.value);
}

function renderDashboard(graph, opts = {}) {
  const esc = CH.esc;
  const multi = multiClientRegistrants(graph);
  const cross = opts.sideA && opts.sideB ? straddling(multi, opts.sideA, opts.sideB) : [];
  const subjects = bySubject(graph);
  const generated = new Date().toISOString().slice(0, 16).replace('T', ' ');

  const crossBlock = !opts.sideA ? '' : (cross.length ? `
    <table>
      <thead><tr><th>Registrant</th><th class="n">Clients</th><th class="n">Filings</th><th>Both sides</th></tr></thead>
      <tbody>
        ${cross.map((r) => `<tr>
          <td><b>${esc(r.name)}</b></td>
          <td class="n">${r.clientCount}</td>
          <td class="n">${r.filings}</td>
          <td class="cl">${r.clients.map((c) => esc(c.name)).join(' · ')}</td>
        </tr>`).join('')}
      </tbody>
    </table>`
    : `<p class="empty">No registrant in the library carries a client matching both patterns.
       That is a finding about your library, not about lobbying.</p>`);

  return `<!-- generated by sentinel connect graph --dashboard -->
<title>Graph dashboard</title>
<style>
  :root {
    --ground:#f6f7f9; --raised:#fff; --ink:#161c24; --muted:#5b6673;
    --rule:#dfe4ea; --warn:#9a4a1c; --warn-bg:#fdf1e8; --accent:#3b6ea5;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --ground:#0f141a; --raised:#161d25; --ink:#e6ebf2; --muted:#98a3b1;
      --rule:#252e39; --warn:#e8a06a; --warn-bg:#2a1a10; --accent:#6fa3d8;
    }
  }
  :root[data-theme="dark"] {
    --ground:#0f141a; --raised:#161d25; --ink:#e6ebf2; --muted:#98a3b1;
    --rule:#252e39; --warn:#e8a06a; --warn-bg:#2a1a10; --accent:#6fa3d8;
  }
  *{box-sizing:border-box}
  body{background:var(--ground);color:var(--ink);margin:0;padding:2rem 1.25rem 5rem;
    font:15px/1.6 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
  .wrap{max-width:62rem;margin:0 auto}
  h1{font-size:1.6rem;margin:0 0 .3rem;letter-spacing:-.01em}
  h2{font-size:1.12rem;margin:2.5rem 0 .4rem}
  .sub{color:var(--muted);margin:0 0 1.5rem;font-size:.9rem}
  .note{color:var(--muted);font-size:.88rem;margin:.3rem 0 1rem;max-width:52rem}
  .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(9rem,1fr));
    gap:1px;background:var(--rule);border:1px solid var(--rule);border-radius:4px;
    overflow:hidden;margin:0 0 .6rem}
  .card{background:var(--raised);padding:.85rem 1rem}
  .card .n{font-size:1.45rem;font-weight:600;font-variant-numeric:tabular-nums;display:block}
  .card .l{font-size:.76rem;color:var(--muted);display:block;margin-top:.15rem}
  .floors{background:var(--warn-bg);border:1px solid var(--rule);border-left:3px solid var(--warn);
    border-radius:4px;padding:.85rem 1rem;margin:1.25rem 0 0;color:var(--ink);font-size:.9rem}
  .floors b{color:var(--warn)}
  .panel{background:var(--raised);border:1px solid var(--rule);border-radius:4px;
    padding:1rem;margin:.75rem 0;overflow-x:auto}
  table{border-collapse:collapse;width:100%;font-size:.9rem}
  th,td{text-align:left;padding:.5rem .6rem;border-bottom:1px solid var(--rule);vertical-align:top}
  th{font-size:.72rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
  td.n,th.n{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
  td.cl{color:var(--muted);font-size:.85rem}
  .empty{color:var(--muted);font-style:italic;margin:.5rem 0}
  .bar-label{font-size:12px;fill:var(--ink)}
  .val{font-size:11px;fill:var(--muted)}
  .axis{stroke:var(--rule)}
  svg{max-width:100%;height:auto}
  footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--rule);
    color:var(--muted);font-size:.84rem}
</style>
<div class="wrap">
  <h1>Graph dashboard</h1>
  <p class="sub">Generated ${esc(generated)} from ${graph.orgs.length.toLocaleString()} organisations in the local library. No network call was made to build this page.</p>

  <div class="cards">
    <div class="card"><span class="n">${graph.orgs.length.toLocaleString()}</span><span class="l">organisations</span></div>
    <div class="card"><span class="n">${graph.filed.length.toLocaleString()}</span><span class="l">sworn filing links</span></div>
    <div class="card"><span class="n">${graph.subjects.length.toLocaleString()}</span><span class="l">searches run</span></div>
    <div class="card"><span class="n">${multi.length.toLocaleString()}</span><span class="l">firms with 2+ clients</span></div>
  </div>

  ${graph.counts_are_floors ? `<div class="floors">
    <b>Every number on this page is a floor.</b> ${graph.truncated_captures} capture(s) hold fewer
    rows than the source reported having. A firm shown with two clients may have forty — you see
    only the ones whose clients you happened to search.
  </div>` : ''}

  <h2>One firm, several clients</h2>
  <p class="note">The only question the sworn data answers on its own. A lobbying filing is a
  statement under 2 U.S.C. 1603–1604 that a named firm lobbied for a named client. It is not
  evidence that the clients know each other.</p>
  <div class="panel">
    ${CH.hbar(multi.map((r) => ({ label: r.name, value: r.clientCount })),
      { limit: 20, format: (v) => `${v} client${v === 1 ? '' : 's'}` })}
  </div>

  ${opts.sideA ? `<h2>Firms carrying both sides</h2>
  <p class="note">Registrants with at least one client matching each of the two patterns you
  supplied. What counts as "both sides" is a judgement about your investigation, not a property
  of lobbying data — the patterns came from you, and the table below is arithmetic on them.</p>
  <div class="panel">${crossBlock}</div>` : ''}

  <h2>What each search contributed</h2>
  <p class="note">This is a chart about <b>your searching</b>, not about the world. A tall bar
  means that search returned many names, which usually means the term was broad.</p>
  <div class="panel">
    ${CH.hbar(subjects, { limit: 20, colour: '#8a7a3b', format: (v) => `${v} name${v === 1 ? '' : 's'}` })}
  </div>

  <footer>
    Every line here is a lead. A name match is not an identification, and nothing on this page has
    been read. Pull the underlying document before any of it is used.
  </footer>
</div>
`;
}

module.exports = { renderDashboard, multiClientRegistrants, straddling, bySubject };
